indico/indico-checkin-pwa

package-lock.json
package.json
src/App.jsx
src/context/SettingsProvider.jsx
src/pages/Settings.jsx
src/pages/Settings.module.scss

- Adds an option to toggle auto-checkin which is saved in local storage

Improve settings page

---

src/App.jsx
src/Components/Background.jsx
src/Components/TopTab.jsx
src/assets/wave_dark_custom.svg
src/assets/wave_light_custom.svg

Just moved it to the app wrapper and set a `min-height` on it.
Also simplified the background image in the navbar so it's one fewer absolutely positioned element ;)

Fix bg color not applying to the whole screen

---

dist/output.css
src/Components/Events/EventItem.tsx
src/Components/Tailwind/LoadingIndicator.tsx
src/Models/EventData.ts
src/db/db.ts
src/pages/Events/EventPage.jsx
src/pages/Events/RegFormPage.tsx
src/pages/Homepage.jsx

- Use uniform looking cards for both events & regforms
- better placement of the loading indicator
- removed card flip - I think it's better to have a settings dropdown on the event/regform page instead

Use uniform look for event & regform cards

---

src/pages/Homepage.jsx

Add icon to `Add event` button

---

src/Components/Tailwind/Button.tsx
src/pages/Homepage.jsx

Improve homepage when there are no events

---

src/Components/Tailwind/Table.tsx
src/Models/EventData.ts
src/db/db.ts
src/db/utils.ts
src/pages/Auth/AuthRedirectPage.jsx
src/pages/Events/AddEventPage.jsx
src/pages/Events/EventPage.jsx
src/pages/Events/RegFormPage.tsx
src/utils/case.ts

- updates some DB tables according to the new checkin API
- improves the regform page and adds more information to it
- simplifies logic related to storing/updating of participants/regforms

DB & regform page updates

---

src/App.jsx
src/Components/BottomTabs.jsx
src/Components/DropdownSettings.jsx
src/Components/Events/EventItem.tsx
src/Components/Tailwind/Typography.tsx

Gives us larger range of colors for dark mode and as a result hover/focus effects don't need to be so bright.
Also decreases the brightness of some text elements.

Make darkmode darker

---

src/Components/BottomTabs.jsx
src/Components/Events/EventItem.tsx
src/Components/Tailwind/LoadingIndicator.tsx
src/Components/Tailwind/Modal/Modal.tsx
src/context/AppStateProvider.tsx
src/db/db.ts
src/db/utils.ts
src/pages/Events/ParticipantPage.tsx
src/pages/Events/fields.tsx
src/utils/date.ts

Participant page now renders registration data. All field types except for accompanying persons are implemented (some extra work will be needed if we want to support those so I'll leave it for another issue)

Render registration data

---

src/App.css
src/Components/BottomTabs.jsx
src/Components/DropdownSettings.jsx
src/Components/Events/EventItem.tsx
src/Components/GrowingTextarea.jsx
src/Components/GrowingTextarea.module.scss
src/Components/Tailwind/Table.tsx
src/Components/Tailwind/Toggle.tsx
src/Components/TopTab.jsx
src/pages/Events/EventPage.jsx
src/pages/Events/ParticipantPage.tsx
src/pages/Events/RegFormPage.tsx
src/pages/Homepage.jsx
src/pages/Scan.jsx
src/utils/wait.ts

- Disabled the blue square overlay for focused elements on Chrome
- Use active/focus instead of hover
- Textarea for participant notes grows automatically based on its contents
- Improved participant search
- Better looking accordions for registration data
- Loading indicator while processing a QR code

Add various UI/UX improvements

---

src/App.jsx

Closes #20 
Just adding some padding to push the content above the bottom navigation

Fix bottom navigation covering content at the bottom

---

Dockerfile
src/Components/Tailwind/Table.tsx
src/index.tsx
src/pages/Events/ParticipantPage.tsx

- Fixes some TS errors
- Adds a Dockerfile

Prepare for deployment

---

.prettierrc.yaml
package-lock.json
package.json
src/Components/Events/EventItem.tsx
src/Components/Tailwind/Modal/Modal.tsx
src/Components/Tailwind/Table.tsx
src/Components/Tailwind/Toggle.tsx
src/pages/Events/ParticipantPage.tsx
src/pages/Events/RegFormPage.tsx
src/pages/Events/fields.tsx
src/pages/Events/utils.tsx
src/pages/LoadingBanner.tsx
src/pages/NotFound.tsx
src/pages/Scan.jsx

The plugin sorts tailwind classes so that the ordering is consistent throughout the codebase.

Add prettier tailwind plugin

---

.husky/pre-commit
README.md
package-lock.json
package.json

Set up husky w/ lint-staged to run eslint/prettier before committing

Add pre-commit hooks

---

.github/workflows/ci.yml
.github/workflows/lighthouse-report-comment.yml
lighthouserc.js

Runs a CI job which creates a [lighthouse](https://developer.chrome.com/docs/lighthouse/overview/) report and adds a link to the PR

Automatically create lighthouse reports for PRs

---

src/Components/Tailwind/Button.tsx
src/Components/Tailwind/Table.tsx
src/Components/Tailwind/filters.tsx
src/pages/Events/RegformPage.tsx
src/utils/case.ts

- Allows users to filter participants by the check-in and registration status + order by the name/registration date.
- Rejected and withdrawn participants are crossed out like in Indico

Allow filtering participants

---

src/Components/QrScanner/QrScannerPlugin.tsx
src/hooks/useMediaQuery.ts
src/pages/scan/Scan.tsx

~~Visible only in development~~. Visible in development and on large viewports (desktops, >1280px)
Useful for testing on a PC

Allow uploading QR code images instead of using the camera

---

src/Components/Tailwind/Button.tsx
src/Components/Tailwind/Modal/Modal.tsx

Deployed here: https://indico-checkin-test-3.app.cern.ch/
Go to the settings tab to see both the error and confirm messages.

Improve the look of modals

---

src/pages/participant/fields.tsx

Show filename if URL is invalid

---

.github/workflows/ci.yml

This bumps `actions/upload-artifact@v3` -> `actions/upload-artifact@v4`

Bump CI dependency

---

src/Components/Tailwind/Table.tsx
src/Components/Tailwind/filters.tsx
src/db/db.ts
src/pages/participant/ParticipantPage.tsx
src/pages/participant/RegistrationTag.tsx
src/pages/regform/RegformPage.tsx
src/pages/scan/scan.test.ts

Show registration tags on participant page

---

src/context/SettingsProvider.tsx
src/db/db.ts
src/hooks/useError.ts
src/pages/Auth/AuthRedirectPage.tsx
src/pages/Auth/utils.ts
src/pages/scan/ScanPage.tsx
src/pages/scan/scan.test.ts
src/pages/scan/scan.ts
src/utils/client.ts

This PR is to allow scanning of custom plugin qr-codes. 
Associated PR: https://github.com/indico/indico/pull/6954
An example of how to implement the signals to test this PR was included in https://github.com/indico/indico/pull/6954

Support scanning custom QR codes from plugins

---

src/App.tsx
src/Components/QrScanner/ExternalQrScanner.tsx
src/Components/QrScanner/QrScannerPlugin.tsx
src/Components/Tailwind/ProgressBar.tsx
src/Components/TopNav.tsx
src/context/SettingsProvider.tsx
src/pages/Settings.tsx
src/pages/participant/ParticipantPage.tsx
src/pages/scan/ScanPage.tsx
src/pages/scan/scan.test.ts
src/pages/scan/scan.ts
src/utils/scan_device.ts

The purpose of this PR is to allow using an External QR code scanning device with the check-in app.

Support external scanners and rapid check-in mode
